### ISSUE TITLE
Uncaught TypeError: ctorParameters.map is not a function

### ISSUE THREAD

**Issue by Shahjalal7311** [zefoy/ngx-swiper-wrapper#10]
node version 5.12.0
npm version 3.8.6

Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:5000/vendor.bundle.js:34625:45)
    at Reflector.parameters (http://localhost:5000/vendor.bundle.js:34760:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:5000/vendor.bundle.js:11460:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:5000/vendor.bundle.js:11425:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:5000/vendor.bundle.js:11200:28)
    at http://localhost:5000/vendor.bundle.js:11269:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:5000/vendor.bundle.js:11262:44)
    at http://localhost:5000/vendor.bundle.js:11250:50
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:5000/vendor.bundle.js:11237:44)
    at http://localhost:5000/vendor.bundle.js:11250:50
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:5000/vendor.bundle.js:11237:44)
    at RuntimeCompiler._compileComponents (http://localhost:5000/vendor.bundle.js:17568:47)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:5000/vendor.bundle.js:17506:37)
    at RuntimeCompiler.compileModuleAsync (http://localhost:5000/vendor.bundle.js:17497:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:5000/vendor.bundle.js:26125:25)
    at PlatformRef_.bootstrapModule (http://localhost:5000/vendor.bundle.js:26107:21)
    at HTMLDocument.main (http://localhost:5000/main.bundle.js:4289:10)
    at ZoneDelegate.invokeTask (http://localhost:5000/polyfills.bundle.js:7335:35)
    at Zone.runTask (http://localhost:5000/polyfills.bundle.js:7224:47)
    at HTMLDocument.ZoneTask.invoke (http://localhost:5000/polyfills.bundle.js:7405:33)

**Comment by sconix** [comment]
Don't see anything in that which would link the error to this library. Anyway the error looks bit like you would have some none compatible combination of angular lib versions etc.
