### ISSUE TITLE
window not defined while generating build angular universal.

### ISSUE THREAD

**Issue by samarmeena** [zefoy/ngx-swiper-wrapper#107]
**I got error every time when I build ngx swiper with angular universal. its shows that window not defined in sipwiper.** 

 I want to use ngx swiper in my universal app too. So provide a solution for this error.

And also the error about outside angular is also occurred with ngx wrapper.

**Comment by sconix** [comment]
What version you are using? Only Swiper 4.x is compatible with SSR and its only supported by the 5.x version of this library.

**Comment by samarmeena** [comment]
I have Swiper 4+ and angular 5+ and other library's are too at latest version.

While ng serve every thing is working fine without any error even the production build is too fine of angular, but while executing angular universal I stuck at this error.

And I have also checked any other possible causes for this error. but I found that only ngx swiper is occurring this error.

**Extra:**  I will be thankful if any one provide me a working example of angular universal with ngx wrapper. the one extra git repository  will be a good help for me. Thanks

**Comment by samarmeena** [comment]
> cd dist && node prerender

ERROR { Error: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined
    at new t (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:171977:185039)
    at createClass (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:13054:20)
    at _createProviderInstance (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:13029:20)
    at createProviderInstance (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:12870:12)
    at createViewNodes (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:14345:53)
    at createRootView (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:14247:5)
    at Object.createProdRootView [as createRootView] (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:14940:12)
    at ComponentFactory_.create (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:11842:46)
    at ComponentFactoryBoundToModule.create (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:4613:29)
    at ViewContainerRef_.createComponent (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:12039:62)
    at resolvePromise (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:169268:31)
    at resolvePromise (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:169232:17)
    at C:\Users\*****\Downloads\universal-starter\dist\prerender.js:169317:17
    at ZoneDelegate.invokeTask (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:168868:31)
    at Object.onInvokeTask (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:5326:33)
    at ZoneDelegate.invokeTask (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:168867:36)
    at Zone.runTask (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:168635:47)
    at drainMicroTaskQueue (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:169041:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  rejection: ReferenceError: window is not defined
    at new t (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:171977:185039)
    at createClass (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:13054:20)
    at _createProviderInstance (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:13029:20)
    at createProviderInstance (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:12870:12)
    at createViewNodes (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:14345:53)
    at createRootView (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:14247:5)
    at Object.createProdRootView [as createRootView] (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:14940:12)
    at ComponentFactory_.create (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:11842:46)
    at ComponentFactoryBoundToModule.create (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:4613:29)
    at ViewContainerRef_.createComponent (C:\Users\*****\Downloads\universal-starter\dist\prerender.js:12039:62),

**Comment by sconix** [comment]
If you are really sure that its because of Swiper then you need to report the issue in Swiper repository. At least quick grep for Swiper 4.x source code did not reveal any direct window usage so not sure why it would cause that error.
