### ISSUE TITLE
SSR (Angular Universal) - MutationObserver / HTMLElement is not defined

### ISSUE THREAD

**Issue by adrienlamotte** [zefoy/ngx-swiper-wrapper#121]
Hello,

When trying to use server side rendering (Angular Universal), I have thoses logs while using your component : 

```
ERROR ReferenceError: MutationObserver is not defined
    at E:\projectwithssr\dist\server.js:170475:28
    at ZoneDelegate.invoke (E:\projectwithssr\dist\server.js:134308:26)
    at Zone.run (E:\projectwithssr\dist\server.js:134058:43)
    at NgZone.runOutsideAngular (E:\projectwithssr\dist\server.js:4847:69)
    at SwiperComponent.ngOnInit (E:\projectwithssr\dist\server.js:170473:19)
    at checkAndUpdateDirectiveInline (E:\projectwithssr\dist\server.js:12365:19)
    at checkAndUpdateNodeInline (E:\projectwithssr\dist\server.js:13868:20)
    at checkAndUpdateNode (E:\projectwithssr\dist\server.js:13811:16)
    at prodCheckAndUpdateNode (E:\projectwithssr\dist\server.js:14514:5)
    at Object.updateDirectives (E:\projectwithssr\dist\server.js:149567:180293)
ERROR ReferenceError: HTMLElement is not defined
    at SwiperConfig.assign (E:\projectwithssr\dist\server.js:169979:77)
    at SwiperComponent.getConfig (E:\projectwithssr\dist\server.js:170504:27)
    at Object.o.ɵvid.e [as updateDirectives] (E:\projectwithssr\dist\server.js:149567:99173)
    at Object.updateDirectives (E:\projectwithssr\dist\server.js:14255:29)
    at checkAndUpdateView (E:\projectwithssr\dist\server.js:13778:14)
    at callViewAction (E:\projectwithssr\dist\server.js:14128:21)
    at execComponentViewsAction (E:\projectwithssr\dist\server.js:14060:13)
    at checkAndUpdateView (E:\projectwithssr\dist\server.js:13784:5)
    at callViewAction (E:\projectwithssr\dist\server.js:14128:21)
    at execEmbeddedViewsAction (E:\projectwithssr\dist\server.js:14086:17)
```

Any idea how to fix that ?

I've looked in your source code, looks like I can find MutationObserver in `swiper.component.ts` and HTMLElement in `swiper.interface.ts` but I don't know what to do with them on server side...

Thank you !

**Comment by sconix** [comment]
I guess you could add some dummy definition for the HTMLElement and just use the directive. I will add checks for those for next version, but it could be 1-2 weeks that I have time to make it. PR's are of course accepted.

**Comment by swapnil-coditas** [comment]
Any updates on this??

**Comment by sconix** [comment]
What do you mean, as you can see this was fixed a long time a go. Latest version have full checks for SSR.
