### ISSUE TITLE
Can't do manually initialize

### ISSUE THREAD

**Issue by Maksi1994** [zefoy/ngx-swiper-wrapper#122]
I use ngx-swiper-wrapper of last version. I have some problem when I'm using him in my page. I think, that i can run manualy intialize in during use. For that i set init: false property in config and i wanted use swiperInstant.init() in my angular component, this solution helped, but when I was reload my component witch have swiper - i view this Error and my application can't work normaly.

> ERROR DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at Dom7.removeClass (webpack-internal:///../../../../swiper/dist/js/swiper.js:126:77)
    at Swiper.removeClasses (webpack-internal:///../../../../swiper/dist/js/swiper.js:3118:7)
    at Swiper.destroy (webpack-internal:///../../../../swiper/dist/js/swiper.js:3685:14)
    at eval (webpack-internal:///../../../../ngx-swiper-wrapper/dist/ngx-swiper-wrapper.es5.js:331:32)
    at ZoneDelegate.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:388:26)
    at Zone.run (webpack-internal:///../../../../zone.js/dist/zone.js:138:43)
    at NgZone.runOutsideAngular (webpack-internal:///../../../core/esm5/core.js:4896:69)
    at SwiperDirective.ngOnDestroy (webpack-internal:///../../../../ngx-swiper-wrapper/dist/ngx-swiper-wrapper.es5.js:330:23)
    at callProviderLifecycles (webpack-internal:///../../../core/esm5/core.js:12910:18)
    at callElementProvidersLifecycles (webpack-internal:///../../../core/esm5/core.js:12871:13)

**Comment by sconix** [comment]
That error comes from the Swiper, I can not help with that so you would need to ask in Swiper issues that what could be causing it and is it a bug etc.

**Comment by Maksi1994** [comment]
Maybe this can help you, i understanded so this mistake happens when i use *ngIf or another similar directive around swiper, and activate manual mode with init:false. 
Swipe ussues  - coudn't help me, developer answered me that problem not relate with "swipe", because this is  ng-swiper-wrapper. It is not their problem.

**Comment by sconix** [comment]
The error happens inside the Swiper so its anyway a bug in the Swiper , but I do understand that the developer is not interested since it happens when used in Angular (something that Swiper was never designed for). Sure there might be a way to add a workaround or prevent the error in this library, but the same goes for you app. You can make a workaround within your app to avoid the error.

I can have a look at some point, but workarounds for internal Swiper errors are not a high priority for me. If you can replicate the error with a Plunker template then I can have a quick look to see if there is something simple to do to avoid the error. I don't sadly have time to look into this without a easy replication.

**Comment by Maksi1994** [comment]
Of course, it's easy. I've made this with your example project =)
http://plnkr.co/edit/sBNUlI0rRu98997pIIM5?p=preview

**Comment by sconix** [comment]
Thanks, I will have quick look tomorrow.
