### ISSUE TITLE
Version 9.0.0 not working with Angular Universal.

### ISSUE THREAD

**Issue by yuveliremil** [zefoy/ngx-swiper-wrapper#252]
All works fine with version ngx-swiper-wrapper@8.0.2
But after upgrade to ngx-swiper-wrapper@9.0.0 I get following error:

```C:\project-name>npm run serve:ssr

> project-name@2.0.0 serve:ssr C:\project-name
> node dist/server/main.js

C:\project-name\node_modules\swiper\js\swiper.js:2696
    var screenWidth = win.screen.width;
                                 ^

TypeError: Cannot read property 'width' of undefined
    at Device (C:\project-name\node_modules\swiper\js\swiper.js:2696:34)
    at C:\project-name\node_modules\swiper\js\swiper.js:2785:4
    at C:\project-name\node_modules\swiper\js\swiper.js:14:83
    at Object.<anonymous> (C:\project-name\node_modules\swiper\js\swiper.js:17:2)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)```

**Comment by philip-firstorder** [comment]
Same error for me, can confirm this.

**Comment by dottodot** [comment]
Yes I'm seeing this too.

**Comment by faropoulos** [comment]
Same thing happens to me as well. Is there any future fix for that;

**Comment by yuveliremil** [comment]
Any update on this?

**Comment by sconix** [comment]
There is no SSR support, I can merge PR's if provided but do not have time to look into it myself.
